### ISSUE TITLE
Random Crash with 1.11.2

### ISSUE THREAD

**Issue by cremshaw** [capnkirok/animania#105]
java.lang.NoSuchMethodError: com.animania.tileentities.TileEntityTrough.getTroughRotation()I
	at com.animania.blocks.BlockInvisiblock.func_180663_b(BlockInvisiblock.java:125)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:565)
	at net.minecraft.world.World.func_180501_a(World.java:335)
	at net.minecraft.world.World.func_175698_g(World.java:390)
	at com.animania.blocks.BlockTrough.func_180663_b(BlockTrough.java:315)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:565)
	at net.minecraft.world.World.func_180501_a(World.java:335)
	at net.minecraft.world.World.func_175655_b(World.java:411)
	at com.animania.entities.cows.EntityAIFindFood.func_75250_a(EntityAIFindFood.java:439)
	at com.animania.entities.cows.EntityAIFindFood.func_75253_b(EntityAIFindFood.java:515)
	at net.minecraft.entity.ai.EntityAITasks.func_75773_a(SourceFile:136)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:108)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:769)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2258)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:573)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:171)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:39)
	at com.animania.entities.cows.EntityCowFriesian.func_70636_d(EntityCowFriesian.java:554)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296)
	at net.minecraft.world.World.func_72866_a(World.java:1963)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1932)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

**Comment by Tschipp** [comment]
Looks like you're trying to call Server code on the Client @capnkirok

**Comment by cremshaw** [comment]
Right, this is from the server crashing. Maybe I'm doing it wrong... Is there a different jar/install for server?

Sent from BlueMail<http://www.bluemail.me/r?b=9479>
On Apr 15, 2017, at 2:30 AM, Tschipp <notifications@github.com<mailto:notifications@github.com>> wrote:

Looks like you're trying to call Server code on the Client @capnkirok<https://github.com/capnkirok>

**Comment by Tschipp** [comment]
No. A fix will be out soon(ish)

**Comment by capnkirok** [comment]
Ok, I put a null check in as well as set it on the server side. I may ask you to test this @Tschipp once I have a build ready (can't test server from Japan). Anyway, fixed in next release.
