### ISSUE TITLE
Multiplayer Animania & TOP Integration Error

### ISSUE THREAD

**Issue by Starza4TW** [capnkirok/animania#298]
It appears there is an error regarding showing an animal's mate and said mate's name when using Animania & The One Probe on a server. This issue does not exist in singleplayer, only in multiplayer.

The error appears in-game as follows:
![2017-08-11_02 11 53](https://user-images.githubusercontent.com/2940976/29202915-84b92b0e-7e3a-11e7-8101-dd4297a78bba.png)

While testing on a standalone server + client, the fml-server-latest.log reports:
```
[02:11:50] [Server thread/DEBUG] [theoneprobe/]: The One Probe catched error: 
java.lang.NoSuchMethodError: net.minecraft.world.World.func_72910_y()Ljava/util/List;
	at com.animania.compat.top.providers.entity.TOPInfoProviderMateable.addProbeInfo(TOPInfoProviderMateable.java:34) ~[TOPInfoProviderMateable.class:?]
	at com.animania.common.entities.cows.EntityBullBase.addProbeInfo(EntityBullBase.java:248) ~[EntityBullBase.class:?]
	at com.animania.compat.top.TOPCompat$2.addProbeEntityInfo(TOPCompat.java:70) ~[TOPCompat$2.class:?]
	at mcjty.theoneprobe.network.PacketGetEntityInfo.getProbeInfo(PacketGetEntityInfo.java:121) ~[PacketGetEntityInfo.class:?]
	at mcjty.theoneprobe.network.PacketGetEntityInfo.access$400(PacketGetEntityInfo.java:32) ~[PacketGetEntityInfo.class:?]
	at mcjty.theoneprobe.network.PacketGetEntityInfo$Handler.handle(PacketGetEntityInfo.java:87) ~[PacketGetEntityInfo$Handler.class:?]
	at mcjty.theoneprobe.network.PacketGetEntityInfo$Handler.lambda$onMessage$0(PacketGetEntityInfo.java:78) ~[PacketGetEntityInfo$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
```

Versions used:
- Minecraft 1.11.2
- Forge 13.20.1.2429
- Animana 1.2.2
- CraftStudio API 0.3.0.86
- The One Probe 1.1x-1.4.14
- CompatLayer 1.11.2-0.2.9

**Comment by capnkirok** [comment]
Sorry for late reply, we're working on it :)
