### ISSUE TITLE
new version crashing server

### ISSUE THREAD

**Issue by dapurewitch** [capnkirok/animania#359]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (sponge.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 9/26/17 1:15 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Animania (animania)
Caused by: java.lang.ClassNotFoundException: com.animania.Animania
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:521)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:552)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:559)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 34 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 3.10.0-327.28.3.el7.x86_64
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1187116880 bytes (1132 MB) / 1760559104 bytes (1679 MB) up to 3728736256 bytes (3556 MB)
	JVM Flags: 1 total; -Xmx4000M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2254 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (server.jar) 
	UC	Forge{12.18.3.2254} [Minecraft Forge] (server.jar) 
	UC	spongeapi{5.2.0-SNAPSHOT-a3257a0} [SpongeAPI] (minecraft.jar) 
	UC	sponge{1.10.2-2254-5.2.0-BETA-2236} [SpongeForge] (sponge.jar) 
	UC	adventuremmo{2.0.5} [AdventureMMO] (AdventureMMO-v2.0.5.jar) 
	UE	animania{1.3.3} [Animania] (animania-1.10.2-1.3.3.jar) 
	UC	aquaculture{1.4.0} [Aquaculture] (Aquaculture-1.10.2-1.4.0.28.jar) 
	UC	backpack{3.0.1} [Backpack] (backpack-3.0.1-1.10.2.jar) 
	UC	BiblioCraft{2.2.4} [BiblioCraft] (BiblioCraft[v2.2.4][MC1.10.2].jar) 
	UC	bungeetablistplus{2.7.4-SNAPSHOT} [BungeeTabListPlus-SpongeBridge] (BungeeTabListPlus_SpongeBridge-2.7.4-SNAPSHOT.jar) 
	UC	carrotshop{1.3} [CarrotShop] (CarrotShop-1.3.jar) 
	UC	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.10.2.jar) 
	UC	cookingforblockheads{4.2.39} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.39.jar) 
	UC	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(25may17).jar) 
	UC	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.3_1.10.2.jar) 
	UC	props{2.4.3} [Decocraft] (Decocraft-2.4.3_1.10.2.jar) 
	UC	discordbridge{2.3.0} [Discord Bridge] (DiscordBridge-2.4.0-all.jar) 
	UC	doggytalents{v1.11.1d} [Doggy Talents] (DoggyTalents-1.10.2-v1.11.1d-universal.jar) 
	UC	nuvotifier{2.3.2.2} [NuVotifier] (EMPSponge.jar) 
	UC	enjin-minecraft-plugin{3.1.0-sponge} [Enjin Minecraft Plugin] (EMPSponge.jar) 
	UC	fastasyncworldedit{development} [ FastAsyncWorldEdit] (FastAsyncWorldEdit-sponge-17.03.24-06f6120-590-11.7.15.jar) 
	UC	worldedit{} [WorldEdit] (FastAsyncWorldEdit-sponge-17.03.24-06f6120-590-11.7.15.jar) 
	UC	JEI{3.14.7.416} [Just Enough Items] (jei_1.10.2-3.14.7.416.jar) 
	UC	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.5.3.jar) 
	UC	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.5.1.jar) 
	UC	holograms{2.2} [Holograms] (holograms-2.2.jar) 
	UC	luckperms{3.0.61} [LuckPerms] (LuckPerms-Sponge-3.0.61.jar) 
	UC	lucky{7.3.0} [Lucky Block] (LuckyBlock_1-10-2_v7-3-0.jar) 
	UC	RadixCore{1.10.2-2.1.3} [RadixCore] (RadixCore-1.10.2-2.1.3-universal.jar) 
	UC	MCA{1.10.2-5.2.3} [Minecraft Comes Alive] (MCA-1.10.2-5.2.3-universal.jar) 
	UC	nucleus{0.26.2-S5.1} [Nucleus] (Nucleus-0.26.2-1.10.2-S5.1-plugin.jar) 
	UC	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
	UC	playershops{1.10.2-1.0.0} [Player Shops] (PlayerShops-1.10.2-1.0.0.jar) 
	UC	prism{3.0.0} [Prism] (Prism-3.0.0-beta2-44-g18fa2a4-all.jar) 
	UC	pjw{0.11.4} [ProjectWorlds] (projectworlds-5.1.0-0.11.4.jar) 
	UC	ruins{16.2} [Ruins Mod] (Ruins-1.10.2.jar) 
	UC	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.10.2-1.1.2.jar) 
	UC	undergroundbiomes{1.0.v.18} [Underground Biomes] (UndergroundBiomesConstructs-1.10-1.0.v.19.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (sponge.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by dapurewitch** [comment]
i just tested it in single play and it crashed it as well ;(

**Comment by capnkirok** [comment]
So, for the record, Animania is not crashing the server or client. It runs fine in client and server environment, and I would have an earful already if this was the case. It could be a bugged version, or could be a conflict with another mod or possibly Sponge. I have 3 suggestions:

1) Try deleting the old Animania (and Config) and downloading a fresh version from CurseForge. See if that works.
2) Try playing it without any other mods and see if it works, then add Sponge, and start adding things back
3) Contact Sponge if it turns out to be Sponge

**Comment by capnkirok** [comment]
The error is nonsensical, it basically says it can't find the main mod class.

**Comment by dapurewitch** [comment]
we have been playing with the older version just fine. its only when we updated the issues came around. we will try your suggestions thank you

**Comment by capnkirok** [comment]
Ok, let me know how it goes.

**Comment by dapurewitch** [comment]
ok the owner helped me out turns out my animania file was bad somehow. he said server is up now :)

**Comment by capnkirok** [comment]
Great! Closing this one ...
