### ISSUE TITLE
Get crash on Entities (goats)

### ISSUE THREAD

**Issue by Foxgreat** [capnkirok/animania#427]
Here's my walkthrough with server-sided crash some about drinking.
[crash-2017-11-12_21.39.58-server.txt](https://github.com/capnkirok/animania/files/1464890/crash-2017-11-12_21.39.58-server.txt)

```
java.lang.Error
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.world.World.func_72964_e(World.java:309)
	at net.minecraft.world.World.func_175726_f(World.java:304)
	at net.minecraft.world.World.getBiomeForCoordsBody(World.java:155)
	at net.minecraft.world.WorldProvider.getBiomeForCoords(WorldProvider.java:375)
	at net.minecraft.world.World.func_180494_b(World.java:148)
	at com.animania.common.entities.goats.ai.EntityAIFindWater.func_75246_d(EntityAIFindWater.java:237)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2347)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at net.minecraft.entity.passive.EntitySheep.func_70636_d(EntitySheep.java:111)
	at com.animania.common.entities.goats.EntityAnimaniaGoat.func_70636_d(EntityAnimaniaGoat.java:380)
	at com.animania.common.entities.goats.EntityBuckBase.func_70636_d(EntityBuckBase.java:234)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2167)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:160)
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zkm000(WorldServer.java:2840)
	at net.minecraft.world.World.func_72866_a(World.java:4134)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1948)
	at net.minecraft.world.World.func_72939_s(World.java:6552)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2209)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Foxgreat** [comment]
MC 1.12.2
Forge 2529
Animania 1.3.6.1

**Comment by capnkirok** [comment]
Thanks. This is the code at this line: 

Biome biomegenbase = temptedEntity.world.getBiome(pos); 

Which means that the biome is undefined and giving a null, probably a worldGen mod you have installed. This is the second time I have seen this though, so I'll have to put in a null check. Weird that a worldGen mod would return null for biome.

**Comment by capnkirok** [comment]
It does look like this is an issue with a WorldGen mod. I found a fix in the BuildCraft git hub here: https://github.com/BuildCraft/BuildCraft/blob/8e538cf91e3d08425b9b4a116bee1ac2435cf49d/common/buildcraft/energy/generation/GenLayerAddOilOcean.java

**Comment by capnkirok** [comment]
I've put the null check in, not sure if it will completely fix it. Check next release.
