### ISSUE TITLE
ClassCastException EntityFerretBase.getAnimalAge

### ISSUE THREAD

**Issue by ctking425** [capnkirok/animania#495]
### Expected Behavior
Expected game not to crash when coming into contact with ferret

### Actual Behavior
Client side crash when ferret is present

### Steps to Reproduce
Have a ferret present. Can't be any more specific since that's all it appears to be.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.10.2
Animania: 1.4.3

java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
	at com.animania.entities.rodents.EntityFerretBase.getAnimalAge(EntityFerretBase.java:319)
	at com.animania.entities.rodents.EntityFerretBase.func_70636_d(EntityFerretBase.java:459)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)

Full Crash Report:
[crash-2017-12-29_20.37.37-client.txt](https://github.com/capnkirok/animania/files/1594113/crash-2017-12-29_20.37.37-client.txt)

**Comment by mageonline** [comment]
I'm getting the same with EntityHedgehogBase....

Stacktrace:
	at com.animania.common.entities.rodents.EntityHedgehogBase.getAge(EntityHedgehogBase.java:268)
	at com.animania.common.entities.rodents.EntityHedgehogBase.func_70636_d(EntityHedgehogBase.java:462)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

**Comment by capnkirok** [comment]
Did you guys add Animania to an existing world that already had custom entities in it? There is an issue with Minecraft and the way it stacks data for entities, and the data index becomes confused. 

If this is the case, would recommend you start a new world, should clear the issue.

**Comment by mageonline** [comment]
I generated new world with the modpack i downloaded from Twitch App. In fact created several worlds to find all crash sooner or later.

**Comment by ctking425** [comment]
Mod was present from the beginning, initial world gen, and hasn't changed since then.

**Comment by capnkirok** [comment]
Well, I don't know what's causing it, but I have changed the code so it works differently. Fixed in next release.
