### ISSUE TITLE
Client Crash related to horse age?

### ISSUE THREAD

**Issue by Izbenn** [capnkirok/animania#520]
### Expected Behavior
Not to crash

### Actual Behavior
crash to desktop

### Steps to Reproduce
Install mods, setup server, connect to server, move around until horses spawn, crash to desktop.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft version 1.12.2
Animania 1.12.2-1.4.4
Multiplayer -  additional mods are loaded, but the excerpt makes it look like error may be Animania specific?

### Screenshots encouraged
No screenshot, but attached should be crash log .... plus a short excerpt here ....

java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
	at com.animania.common.entities.horses.EntityAnimaniaHorse.getAge(EntityAnimaniaHorse.java:305)
	at com.animania.common.entities.horses.EntityFoalBase.func_70636_d(EntityFoalBase.java:265)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.passive.AbstractHorse.func_70071_h_(AbstractHorse.java:682)
	at net.minecraft.entity.passive.EntityHorse.func_70071_h_(EntityHorse.java:209)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[crash-2018-01-22_12.33.17-client.txt](https://github.com/capnkirok/animania/files/1652984/crash-2018-01-22_12.33.17-client.txt)

**Comment by capnkirok** [comment]
It doesn't happen to everyone, and it can be a different animal entirely. Seems to only happen when there is another mod that adds custom entities and on servers. But it only appears to be this one parameter (age). Let me know if you run into any other issues.

**Comment by SniperHauss89** [comment]
Hello, This is odd as I get a very similar crash server side with horses but it looks like my points to getColorNumber.

Description: Ticking entity

java.lang.ClassCastException: com.google.common.base.Absent cannot be cast to java.lang.Integer
	at com.animania.common.entities.horses.EntityAnimaniaHorse.getColorNumber(EntityAnimaniaHorse.java:337)
	at com.animania.common.entities.horses.EntityStallionBase.func_70636_d(EntityStallionBase.java:337)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.passive.AbstractHorse.func_70071_h_(AbstractHorse.java:682)
	at net.minecraft.entity.passive.EntityHorse.func_70071_h_(SourceFile:209)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I hope this can be fixed pretty swiftly as I love the mod and the horses a nice touch. ^.^

**Comment by capnkirok** [comment]
I'm worried that the entire way of using data needs to be swapped out. This error seems to appear on some servers that are also using mods that introduce custom entities. Doesn't happen all the time, only some of the time (the worst kind of bugs).

There's nothing wrong with my code, tbh. It's just that Minecraft stacks this data type like an inbox and sometimes it gets confused and gets the wrong entry. In this case, it's trying to cast the UUID of something to the color number. No reason it should ever do that. It may take a longer fix.

**Comment by capnkirok** [comment]
I have reached out to our friends at Forge to see if there's another approach. It appears to be a problem cause by other mods, but honestly, have been dealing with this since launch. Would prefer a more adaptive solution than asking other modders to change.

**Comment by Thyriel** [comment]
Someone using my modpack has the exact same problem (getColorNumber crash) on his 1.12.2 server with Animania 1.3.6 and sent me that crashreport:
http://textuploader.com/dmn7f

Seems to me it's a pretty rare kind of combination that leads to that crash. At least i never had it in like hundred of hours playing that mod combination and no one else ever reported a crash like that to me.

**Comment by capnkirok** [comment]
It only occurs in:
- Multiplayer server
- When there are other mods that add custom entities

**Comment by jimnordb** [comment]
Having this crash with a lot of mods.. is there some coremod changing stuff?

**Comment by capnkirok** [comment]
See test link at bottom of this thread.
https://github.com/capnkirok/animania/issues/550

**Comment by capnkirok** [comment]
Fixed in next release (using error trapping and forcing a valid value)
