### ISSUE TITLE
Client Crash - Ticking entity rodent 1.10.2 Server

### ISSUE THREAD

**Issue by AdaraChristine** [capnkirok/animania#531]
### Expected Behavior
Not to crash client

### Actual Behavior
crashes client

### Version of Minecraft, version of Animania, Single Player or Server
Animania-1.10.2-1.4.4
Minecraft 1.10.2
multiplayer server

### Screenshots encouraged

Time: 1/24/18 3:51 PM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
	at com.animania.entities.rodents.EntityHamster.isHamsterSitting(EntityHamster.java:870)
	at com.animania.entities.rodents.EntityHamster.func_70636_d(EntityHamster.java:644)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at com.animania.entities.rodents.EntityHamster.func_70071_h_(EntityHamster.java:804)
	at net.minecraft.world.World.func_72866_a(World.java:1967)
	at net.minecraft.world.World.func_72870_g(World.java:1937)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[crash-2018-01-24_15.51.03-client.txt](https://github.com/capnkirok/animania/files/1662249/crash-2018-01-24_15.51.03-client.txt)

**Comment by Tschipp** [comment]
Related to #520

**Comment by capnkirok** [comment]
Yeah, gonna have to make a permanent change here, I don't think duct tape is going to work much longer.

**Comment by capnkirok** [comment]
Fixed in next release...

**Comment by AdaraChristine** [comment]
Thank you everyone for all your hard work
