### ISSUE TITLE
ClassCastException EntityHamster.isHamsterSitting

### ISSUE THREAD

**Issue by ciak2009** [capnkirok/animania#534]
### Expected Behavior
Expected game not to crash when coming into contact with hamster

### Actual Behavior
Client-side crash when hamster is present

### Steps to Reproduce
Have a hamster present. Can't be any more specific since that's all it appears to be.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft: 1.10.2 
Animania:1.4.4
Forge 2477 Server

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
	at com.animania.entities.rodents.EntityHamster.isHamsterSitting(EntityHamster.java:870)
	at com.animania.entities.rodents.EntityHamster.func_70636_d(EntityHamster.java:644)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at com.animania.entities.rodents.EntityHamster.func_70071_h_(EntityHamster.java:804)
	at net.minecraft.world.World.func_72866_a(World.java:1967)
	at net.minecraft.world.World.func_72870_g(World.java:1937)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Full crash report:
[crash-2018-01-27_16.16.35-client.txt](https://github.com/capnkirok/animania/files/1670554/crash-2018-01-27_16.16.35-client.txt)

**Comment by capnkirok** [comment]
This is the same error many people are experience right now due to Heap Corruption.... happens on server when other mods are present that manipulate Data Parameters. Working on a permanent solution.

#531

**Comment by capnkirok** [comment]
See test link at bottom of this thread
https://github.com/capnkirok/animania/issues/550
