### ISSUE TITLE
Got this Errors on startup on 1.11.2 Forge 13.20.0.2252

### ISSUE THREAD

**Issue by Baalith** [capnkirok/animania#93]
Just a little portion of my startup log:

[19:17:01] [Client thread/WARN] [FML]: * Unknown recipe class! com.animania.recipes.CheeseRecipe1 Modders need to register their recipe types with net.minecraftforge.oredict.RecipeSorter
[19:17:01] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.getPriority(RecipeSorter.java:241)
[19:17:01] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:176)
[19:17:01] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:55)
[19:17:01] [Client thread/WARN] [FML]: *  at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
[19:17:01] [Client thread/WARN] [FML]: *  at java.util.TimSort.sort(TimSort.java:234)
[19:17:01] [Client thread/WARN] [FML]: *  at java.util.Arrays.sort(Arrays.java:1512)...

Hope you can fix this :)

**Comment by Tschipp** [comment]
@capnkirok This is not really an error, just some info. To fix this, call RecipeSorter.register("cheeseRecipe", CheeseRecipe1.class, Category.SHAPELESS, "")
That last parameter is a String called dependencies. Idk what it does, i just leave it blank and it seems to remove the error and still works ingame.

**Comment by capnkirok** [comment]
Yeah, I have a typo in mine. Thx @Tschipp .

**Comment by capnkirok** [comment]
@Tschipp the last string determines where it appears in the recipe list. So, for mine, I have them as "after:minecraft:shapeless", which places it in the array right after the MC shapeless recipes.

And the problem was one of capitalization. I was using camel case for the recipe names, which is a no-no in 1.11.2 (e.g., changed ""animania:cheeseWheelHolstein" to "animania:cheesewheelholstein") which fixed the problem. Explains why it worked fine in 1.10 but not in 1.11.

Fixed in 1.0.4.7

**Comment by Tschipp** [comment]
Ahh, I see, thanks
