### ISSUE TITLE
Animania Causing Repeated Crashes

### ISSUE THREAD

**Issue by FiniteParadox22** [capnkirok/animania#96]
I am playing on ATLauncher in a modified version of their MechMagic modpack and have added Animania, I continually crash with the same error coming from an Animania Pig of some sort (It has changed since I first removed and readded the mod) and something to do with mud

This is the exact location of the error and I will attach the error logs below

[07/4/2017 20:53:02 PM] -- Head --
[07/4/2017 20:53:02 PM] Thread: Client thread
[07/4/2017 20:53:02 PM] Stacktrace:
[07/4/2017 20:53:02 PM] 	at com.animania.entities.pigs.EntityAIFindMud.func_75250_a(EntityAIFindMud.java:239)
[07/4/2017 20:53:02 PM] 	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
[07/4/2017 20:53:02 PM] 	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:900)
[07/4/2017 20:53:02 PM] 	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2183)
[07/4/2017 20:53:02 PM] 	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:685)
[07/4/2017 20:53:02 PM] 	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
[07/4/2017 20:53:02 PM] 	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:41)
[07/4/2017 20:53:02 PM] 	at com.animania.entities.pigs.EntityHogOldSpot.func_70636_d(EntityHogOldSpot.java:739)
[07/4/2017 20:53:02 PM] 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
[07/4/2017 20:53:02 PM] 	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
[07/4/2017 20:53:02 PM] 	at net.minecraft.world.World.func_72866_a(World.java:1964)
[07/4/2017 20:53:02 PM] 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
[07/4/2017 20:53:02 PM] 	at net.minecraft.world.World.func_72870_g(World.java:1934)
[07/4/2017 20:53:02 PM] 
[07/4/2017 20:53:02 PM] -- Entity being ticked --
[07/4/2017 20:53:02 PM] Details:
[07/4/2017 20:53:02 PM] 	Entity Type: animania.HogOldSpot (com.animania.entities.pigs.EntityHogOldSpot)
[07/4/2017 20:53:02 PM] 	Entity ID: 30104
[07/4/2017 20:53:02 PM] 	Entity Name: Old Spot Hog
[07/4/2017 20:53:02 PM] 	Entity's Exact location: 174.89, 63.00, 45.83
[07/4/2017 20:53:02 PM] 	Entity's Block location: World: (174,63,45), Chunk: (at 14,3,13 in 10,2; contains blocks 160,0,32 to 175,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
[07/4/2017 20:53:02 PM] 	Entity's Momentum: 0.00, -0.08, 0.00
[07/4/2017 20:53:02 PM] 	Entity's Passengers: []
[07/4/2017 20:53:02 PM] 	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

ERROR LOGS:
[crash-2017-04-07_20.52.59-server.txt](https://github.com/capnkirok/animania/files/907211/crash-2017-04-07_20.52.59-server.txt)

**Comment by Tschipp** [comment]
@capnkirok Looks like a NullPointer. Should be easy to fix

**Comment by capnkirok** [comment]
I think the clue here is the Vehicle. I have a null pointer check on the block, which is what this AI is looking for (a mud block), but the error here is that the vehicle registered with this pig is null... very strange. Will look deeper into the entity.

**Comment by Tschipp** [comment]
Vehicle? What vehicle?

**Comment by capnkirok** [comment]
That is exactly the problem, ha! Vanilla pigs can be vehicles... and my pig code still has some of that left in there (I toyed with keeping that in). I think it's causing problems.

**Comment by capnkirok** [comment]
Actually, I just reviewed this one, and this was fixed in an earlier release. @FiniteParadox22 , please update to the latest version of Animania, you are on 1.0.1a, where this has been fixed.
